### ISSUE TITLE
有没有可能加入一个功能？

### ISSUE THREAD

**Issue by Tinhone** [FoundTheWOUT/bilibili-evolved-doc#2]
![图片](https://user-images.githubusercontent.com/81268244/172833436-4a393ee6-cb29-487e-9515-70c8593abe4e.png)

https://bilibili-evolved-doc.vercel.app/user/features#%E7%BB%84%E4%BB%B6
如图，有没有可能在此处加入一个“源代码仓库”按钮？具体可以跳转到 https://github.com/the1812/Bilibili-Evolved/tree/master/registry/lib/components/feeds/copy-link 这种的？

**Comment by FoundTheWOUT** [comment]
这部分内容是从上游仓库直接拉的，所以不好加按钮。我把这个功能实现到了名称上，现在点组件的名称就可以跳到仓库的代码。

**Comment by Tinhone** [comment]
感谢！辛苦了！
